trigger:
  branches:
    include:
      - main
      - feature*

pr:
  - master

pool:
  vmImage: 'windows-latest'

variables:
- group: TWPC.Shared

stages:
- stage: Test
  displayName: 'Deploy Test'
  jobs:
  - job: 'Review Infrastructure'
    displayName: 'Review Infrastructure'
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  - job: 'Deploy'
    dsiplayName: 'Deploy Infrastructure'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      

- stage: Prod
  displayName: 'Deploy Production'
  jobs:
  - job: 'Review Infrastructure'
    displayName: 'Review Infrastructure'
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  - job: 'Deploy'
    dsiplayName: 'Deploy Infrastructure'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
