trigger:
  branches:
    include:
      - main
      - feature*

pr:
  - master

pool:
  vmImage: 'windows-latest'

variables:
- group: TWPC.Shared

stages:
- stage: Dev
  displayName: 'Deploy Dev'
  variables:
  - group: TWPC.Dev

  jobs:
  - job: 'Review_Infrastructure'
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
    steps:

    - task: Pulumi@1
      displayName: 'Review Infrastructure'
      inputs:
        azureSubscription: $(azure.service.principal)
        command: "preview"
        cwd: $(pulumi.working.directory)
        stack: $(pulumi.stack.name)

  - job: 'Deploy_Infrastructure'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - job: 'Publish_Website'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      
- stage: Test
  displayName: 'Deploy Test'
  jobs:
  - job: 'Review_Infrastructure'
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  - job: 'Deploy_Infrastructure'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - job: 'Publish_Website'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- stage: Prod
  displayName: 'Deploy Production'
  jobs:
  - job: 'Review_Infrastructure'
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  - job: 'Deploy_Infrastructure'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - job: 'Publish_Website'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
