trigger:
  branches:
    include:
      - main
      - feature*

pr:
  - master

pool:
  vmImage: 'windows-latest'

variables:
- group: TWPC.Shared

stages:

- stage: Dev
  displayName: 'Development'
  variables:
  - group: TWPC.Dev
  - name: twpc.environment
    value: $(azure.environment)

  jobs:
  - deployment: 'Deploy_Dev'
    displayName: 'Deploy Development'
    environment: twpc.environment
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Pulumi@1
              displayName: 'Review Infrastructure'
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'preview'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)

            - task: Pulumi@1
              displayName: 'Deploy Infrastructure'
              condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'deploy'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)
      
- stage: Test
  displayName: 'Test'
  variables:
  - group: TWPC.Test
  - name: twpc.environment
    value: $(azure.environment)

  jobs:
  - deployment: 'Deploy_Test'
    displayName: 'Deploy Test'
    environment: twpc.environment
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Pulumi@1
              displayName: 'Review Infrastructure'
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'preview'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)

            - task: Pulumi@1
              displayName: 'Deploy Infrastructure'
              condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'deploy'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)

- stage: Prod
  displayName: 'Production'
  variables:
  - group: TWPC.Test
  - name: twpc.environment
    value: $(azure.environment)

  jobs:
  - deployment: 'Deploy_Prod'
    displayName: 'Deploy Production'
    environment: twpc.environment
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Pulumi@1
              displayName: 'Review Infrastructure'
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'preview'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)

            - task: Pulumi@1
              displayName: 'Deploy Infrastructure'
              condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'deploy'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)
