trigger:
  branches:
    include:
      - main
      - feature*

pr:
  - master

pool:
  vmImage: 'windows-latest'

variables:
- group: TWPC.Shared

stages:

  # Should always run
- stage: Dev
  displayName: 'Development'
  variables:
  - group: TWPC.Dev
  - name: twpc.environment
    value: $(azure.environment)

  jobs:
  - deployment: 'Deploy_Dev'
    displayName: 'Deploy Development'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Pulumi@1
              displayName: 'Review Infrastructure'
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'preview'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)

            - task: Pulumi@1
              displayName: 'Deploy Infrastructure'
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'up'
                args: '--yes --skip-preview'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)
      
  # Depends on Deploy_Dev only Deploys Infrastrucure from Main
- stage: Test
  displayName: 'Test'
  dependsOn: Dev
  variables:
  - group: TWPC.Test
  - name: twpc.environment
    value: $(azure.environment)

  jobs:
  - deployment: 'Deploy_Test'
    displayName: 'Deploy Test'
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Pulumi@1
              displayName: 'Review Infrastructure'
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'preview'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)

            - task: Pulumi@1
              displayName: 'Deploy Infrastructure'
              condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'up'
                args: '--yes --skip-preview'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)

  # Depends on Deploy_Test should only run main branch
- stage: Prod
  displayName: 'Production'
  dependsOn: Test
  variables:
  - group: TWPC.Prod
  - name: twpc.environment
    value: $(azure.environment)

  jobs:
  - deployment: 'Deploy_Prod'
    displayName: 'Deploy Production'
    environment: 'Prod'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Pulumi@1
              displayName: 'Deploy Infrastructure'
              inputs:
                azureSubscription: $(azure.service.principal)
                command: 'up'
                args: '--yes --skip-preview'
                cwd: $(pulumi.working.directory)
                stack: $(pulumi.stack.name)
