trigger:
  branches:
    include:
      - main
      - feature*

pr:
  - master

pool:
  vmImage: 'windows-latest'

variables:
- group: TWPC.Shared

stages:
- stage: Review
  displayName: 'Review Infrastructure'
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
      

- stage: Deploy
  displayName: 'Deploy Infrastructure'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')